# Generated by Django 5.2.7 on 2025-10-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nama',
            field=models.CharField(default='Admin Default', max_length=100),
            preserve_default=False,
        ),
    ]
