# Generated by Django 5.2.7 on 2025-10-28 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0002_user_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis_lama', models.CharField(blank=True, max_length=20, null=True)),
                ('nama', models.CharField(max_length=100)),
                ('tahun_lulus', models.IntegerField()),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('info_terkini', models.TextField(blank=True, null=True)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('nuptk', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('agama', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tanggal_mulai_kerja', models.DateField(blank=True, null=True)),
                ('status_kepegawaian', models.CharField(choices=[('PNS', 'PNS'), ('GTK Honorer', 'GTK Honorer'), ('Guru Yayasan', 'Guru Yayasan')], max_length=20)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guru_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.IntegerField()),
                ('nama_kelas', models.CharField(max_length=10)),
                ('ruangan', models.CharField(blank=True, max_length=50, null=True)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah')),
                ('wali_kelas', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wali_kelas_profile', to='sekolah.guru')),
            ],
            options={
                'unique_together': {('sekolah', 'tingkat', 'nama_kelas')},
            },
        ),
        migrations.CreateModel(
            name='Ortu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ayah', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_ibu', models.CharField(blank=True, max_length=100, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ortu_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True)),
                ('jabatan', models.CharField(max_length=100)),
                ('tanggal_mulai_kerja', models.DateField(blank=True, null=True)),
                ('status_kepegawaian', models.CharField(choices=[('PNS', 'PNS'), ('GTK Honorer', 'GTK Honorer'), ('Karyawan Yayasan', 'Karyawan Yayasan')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pegawai_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=20)),
                ('nisn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=10)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('agama', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat_jalan', models.TextField(blank=True, null=True)),
                ('rt_rw', models.CharField(blank=True, max_length=10, null=True)),
                ('kelurahan', models.CharField(blank=True, max_length=50, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=50, null=True)),
                ('kota_kabupaten', models.CharField(blank=True, max_length=50, null=True)),
                ('provinsi', models.CharField(blank=True, max_length=50, null=True)),
                ('kode_pos', models.CharField(blank=True, max_length=10, null=True)),
                ('no_hp_siswa', models.CharField(blank=True, max_length=20, null=True)),
                ('nama_kontak_darurat', models.CharField(blank=True, max_length=100, null=True)),
                ('nomor_kontak_darurat', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('status_siswa', models.CharField(choices=[('Aktif', 'Aktif'), ('Pindah', 'Pindah'), ('Lulus', 'Lulus'), ('Cuti', 'Cuti'), ('Dikeluarkan', 'Dikeluarkan')], default='Aktif', max_length=15)),
                ('tanggal_masuk', models.DateField()),
                ('tanggal_keluar', models.DateField(blank=True, null=True)),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siswa', to='sekolah.kelas')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siswa_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Ditutup', 'Ditutup'), ('Arsip', 'Arsip')], default='Arsip', max_length=10)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah')),
            ],
            options={
                'unique_together': {('sekolah', 'nama')},
            },
        ),
    ]
