# Generated by Django 5.2.7 on 2025-10-28 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0003_alumni_guru_kelas_ortu_pegawai_siswa_tahunajaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('penulis', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CitaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_cita_cita', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hobi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_hobi', models.CharField(max_length=100, unique=True)),
                ('kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mapel', models.CharField(max_length=10, unique=True)),
                ('nama_mapel', models.CharField(max_length=100, unique=True)),
                ('kelompok', models.CharField(blank=True, max_length=50, null=True)),
                ('kkm', models.IntegerField(default=75)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penerbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penerbit', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuruMapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.buku')),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.guru')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.mapel')),
            ],
        ),
        migrations.AddField(
            model_name='buku',
            name='mapel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.mapel'),
        ),
        migrations.AddField(
            model_name='buku',
            name='penerbit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sekolah.penerbit'),
        ),
        migrations.CreateModel(
            name='SiswaCitaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.citacita')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='SiswaHobi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.hobi')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='SiswaOrtu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubungan', models.CharField(choices=[('Ayah', 'Ayah'), ('Ibu', 'Ibu'), ('Wali', 'Wali')], max_length=10)),
                ('ortu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.ortu')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.siswa')),
            ],
        ),
    ]
