# Generated by Django 5.2.7 on 2025-10-28 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0004_buku_citacita_hobi_mapel_penerbit_gurumapel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gurumapel',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.kelas'),
        ),
        migrations.AlterUniqueTogether(
            name='gurumapel',
            unique_together={('guru', 'mapel', 'kelas')},
        ),
    ]
