# Generated by Django 5.2.7 on 2025-10-28 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0005_gurumapel_kelas_alter_gurumapel_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='KomponenNilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_komponen', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('Pengetahuan', 'Pengetahuan'), ('Keterampilan', 'Keterampilan')], max_length=15)),
                ('bobot', models.IntegerField()),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah')),
            ],
            options={
                'unique_together': {('sekolah', 'nama_komponen')},
            },
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_akhir_pengetahuan', models.IntegerField(blank=True, null=True)),
                ('nilai_akhir_keterampilan', models.IntegerField(blank=True, null=True)),
                ('predikat_pengetahuan', models.CharField(blank=True, max_length=10, null=True)),
                ('predikat_keterampilan', models.CharField(blank=True, max_length=10, null=True)),
                ('deskripsi_pengetahuan', models.TextField(blank=True, null=True)),
                ('deskripsi_keterampilan', models.TextField(blank=True, null=True)),
                ('catatan_sikap', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guru_mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.gurumapel')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.mapel')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.siswa')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.tahunajaran')),
            ],
            options={
                'unique_together': {('siswa', 'mapel', 'tahun_ajaran')},
            },
        ),
        migrations.CreateModel(
            name='PerizinanSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('waktu_keluar', models.DateTimeField()),
                ('waktu_kembali', models.DateTimeField(blank=True, null=True)),
                ('alasan', models.TextField(blank=True, null=True)),
                ('keterangan_akhir', models.TextField(blank=True, null=True)),
                ('pemberi_izin', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Keluar', 'Keluar'), ('Kembali', 'Kembali'), ('Tidak Kembali', 'Tidak Kembali')], default='Keluar', max_length=15)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.siswa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Terlambat', 'Terlambat'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Alpha', 'Alpha')], max_length=15)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('waktu_input', models.DateTimeField(auto_now_add=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.siswa')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.tahunajaran')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('siswa', 'tanggal')},
            },
        ),
        migrations.CreateModel(
            name='NilaiDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.IntegerField()),
                ('komponen_nilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.komponennilai')),
                ('nilai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sekolah.nilai')),
            ],
            options={
                'unique_together': {('nilai', 'komponen_nilai')},
            },
        ),
    ]
