# Generated by Django 5.2.7 on 2025-10-29 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0006_komponennilai_nilai_perizinansiswa_absensi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JamPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sesi', models.CharField(max_length=50)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('urutan', models.IntegerField()),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah')),
            ],
            options={
                'unique_together': {('sekolah', 'urutan')},
            },
        ),
        migrations.CreateModel(
            name='KeuanganKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jenis', models.CharField(choices=[('Pemasukan', 'Pemasukan'), ('Pengeluaran', 'Pengeluaran')], max_length=20)),
                ('keterangan', models.TextField()),
                ('nominal', models.IntegerField()),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.kelas')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.tahunajaran')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('isi_log', models.TextField()),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.kelas')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.tahunajaran')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_program', models.CharField(max_length=150)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('tanggal_mulai', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Rencana', 'Rencana'), ('Berjalan', 'Berjalan'), ('Selesai', 'Selesai'), ('Batal', 'Batal')], default='Rencana', max_length=20)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.kelas')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.tahunajaran')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=10)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.guru')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.kelas')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.mapel')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.tahunajaran')),
                ('jam_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.jampelajaran')),
            ],
            options={
                'unique_together': {('kelas', 'tahun_ajaran', 'hari', 'jam_pelajaran')},
            },
        ),
        migrations.CreateModel(
            name='OrganisasiKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=50)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.siswa')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.tahunajaran')),
            ],
            options={
                'unique_together': {('kelas', 'tahun_ajaran', 'jabatan')},
            },
        ),
        migrations.CreateModel(
            name='PiketKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=10)),
                ('tugas', models.CharField(blank=True, max_length=100, null=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.kelas')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.siswa')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.tahunajaran')),
            ],
            options={
                'unique_together': {('kelas', 'tahun_ajaran', 'siswa', 'hari')},
            },
        ),
    ]
