# Generated by Django 5.2.7 on 2025-10-29 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0007_jampelajaran_keuangankelas_logkelas_programkelas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=200)),
                ('tanggal_mulai', models.DateTimeField(blank=True, null=True)),
                ('tanggal_selesai', models.DateTimeField(blank=True, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.unit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('aktivitas', models.TextField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitAnggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_bergabung', models.DateField()),
                ('jabatan_di_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('siswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.siswa')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.unit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('unit', 'siswa'), name='unique_unit_siswa'), models.UniqueConstraint(fields=('unit', 'user'), name='unique_unit_user')],
            },
        ),
    ]
