# Generated by Django 5.2.7 on 2025-10-29 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0008_unitkegiatan_unitlog_unitanggota'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkstrakurikulerNilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ekskul', models.CharField(max_length=100)),
                ('predikat', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=5)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.siswa')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.tahunajaran')),
            ],
            options={
                'unique_together': {('siswa', 'tahun_ajaran', 'nama_ekskul')},
            },
        ),
        migrations.CreateModel(
            name='Raport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_raport', models.CharField(choices=[('Tengah Semester', 'Tengah Semester'), ('Akhir Semester', 'Akhir Semester')], max_length=20)),
                ('rata_nilai_pengetahuan', models.IntegerField(blank=True, null=True)),
                ('rata_nilai_keterampilan', models.IntegerField(blank=True, null=True)),
                ('ranking_kelas', models.IntegerField(blank=True, null=True)),
                ('total_hadir', models.IntegerField(default=0)),
                ('total_sakit', models.IntegerField(default=0)),
                ('total_izin', models.IntegerField(default=0)),
                ('total_alpha', models.IntegerField(default=0)),
                ('catatan_wali_kelas', models.TextField(blank=True, null=True)),
                ('catatan_ekstrakurikuler', models.TextField(blank=True, null=True)),
                ('status_raport', models.CharField(choices=[('Draft', 'Draft'), ('Menunggu Persetujuan', 'Menunggu Persetujuan'), ('Disetujui', 'Disetujui'), ('Diterbitkan', 'Diterbitkan')], default='Draft', max_length=20)),
                ('tanggal_disetujui', models.DateTimeField(blank=True, null=True)),
                ('pdf_link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.siswa')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.tahunajaran')),
            ],
            options={
                'unique_together': {('siswa', 'tahun_ajaran', 'jenis_raport')},
            },
        ),
    ]
