# Generated by Django 5.2.7 on 2025-10-29 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0009_ekstrakurikulernilai_raport'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jenis', models.CharField(max_length=100)),
                ('nominal_default', models.IntegerField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah')),
            ],
            options={
                'unique_together': {('sekolah', 'nama_jenis')},
            },
        ),
        migrations.CreateModel(
            name='PengeluaranLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pengeluaran', models.DateField()),
                ('kategori', models.CharField(max_length=50)),
                ('keterangan', models.TextField()),
                ('nominal', models.IntegerField()),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=20)),
                ('nominal_tagihan', models.IntegerField()),
                ('tanggal_jatuh_tempo', models.DateField(blank=True, null=True)),
                ('status_tagihan', models.CharField(choices=[('Belum Lunas', 'Belum Lunas'), ('Lunas', 'Lunas'), ('Dibatalkan', 'Dibatalkan')], default='Belum Lunas', max_length=15)),
                ('jenis_pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.jenispembayaran')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.siswa')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.tahunajaran')),
            ],
            options={
                'unique_together': {('siswa', 'jenis_pembayaran', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='PembayaranLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal_dibayar', models.IntegerField()),
                ('tanggal_bayar', models.DateTimeField(auto_now_add=True)),
                ('metode_pembayaran', models.CharField(max_length=20)),
                ('bukti_pembayaran', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.tagihan')),
            ],
        ),
    ]
