# Generated by Django 5.2.7 on 2025-10-29 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0010_jenispembayaran_pengeluaranlog_tagihan_pembayaranlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenerimaanInsidentilLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_penerimaan', models.DateField()),
                ('kategori', models.CharField(max_length=50)),
                ('keterangan', models.TextField()),
                ('nominal', models.IntegerField()),
                ('sekolah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
